export enum ResponseCodes {
    /* ===== Public [1000 - 1099] ===== */
    PUBLIC_REQUEST_PROCESSED_SUCCESS = 1000,
    PUBLIC_REQUEST_PROCESSED_FAILED_ERR,
    PUBLIC_VALIDATION_ERR,
    PUBLIC_RECAPTCHA_VALIDATION_FAILED_ERR,
    PUBLIC_INSUFFICIENT_CREDITS_ERR,
    PUBLIC_RATE_LIMIT_EXCEEDED_ERR,

    /* ===== Authentication [1100 - 1199] ===== */
    AUTH_INVALID_CREDENTIALS = 1100,
    AUTH_USER_SIGNUP_SUCCESS,
    AUTH_SIGNUP_CONFIRMATION_CODE_SENT_SUCCESS,
    AUTH_FORGOT_PASSWORD_CODE_SENT_SUCCESS,
    AUTH_RESET_PASSWORD_SUCCESS,
    AUTH_RECAPTCHA_VALIDATION_FAILED_ERR,
    AUTH_SIGNUP_EMAIL_EXISTS_ERR,
    AUTH_WRONG_SIGNUP_CONFIRMATION_CODE_ERR,
    AUTH_USER_ALREADY_CONFIRMED_ERR,
    AUTH_USER_SIGNIN_NO_ACCOUNT_ERR,
    AUTH_USER_SIGNIN_WRONG_CREDENTIALS_ERR,
    AUTH_USER_UNCONFIRMED_ERR,
    AUTH_USER_AUTHORIZATION_FAILED_ERR,
    AUTH_RESET_PASSWORD_WRONG_CODE_ERR,
    AUTH_EMAIL_DOMAIN_VERIFICATION_FAILED_ERR,
    /* ===== User [1200 - 1299] ===== */
    USER_API_KEY_REGENERATED_SUCCESS = 1200,
    USER_ACTIVITY_CREATED_SUCCESS,
    USER_NOT_FOUND_ERR,
    USER_SUSPENDED_ERR,
    USER_DELETED_ERR,

    /* ===== Bulks [1300 - 1399] ===== */
    BULK_LIST_FETCHED = 1300,
    BULK_INFO_FETCHED,
    BULK_DOWNLOAD_SUCCESS,
    BULK_NOT_FOUND_ERR,
    BULK_DELETED_SUCCESS,
    BULK_IS_PROCESSING_ERR,

    /* ===== ApiLogs [1400 - 1499] ===== */
    API_LOGS_LIST_FETCHED = 1400,

    /* ===== Plans [1500 - 1599] ===== */
    PLANS_LIST_FETCHED = 1500,
    PLAN_NOT_FOUND_ERR,

    /* ===== Subscriptions [1600 - 1699] ===== */
    SUBSCRIPTIONS_LIST_FETCHED = 1600,
    SUBSCRIPTIONS_NEW_CHECKOUT_SESSION_CREATED,

    /* ===== Integrations [1700 - 1799] ===== */
    INTEGRATIONS_ZOHO_CONNECTION_SUCCESS = 1700,
    INTEGRATIONS_ZOHO_DISCONNECTION_SUCCESS,
    INTEGRATIONS_HUBSPOT_CONNECTION_SUCCESS,
    INTEGRATIONS_HUBSPOT_DISCONNECTION_SUCCESS,
    INTEGRATIONS_SALESFORCE_CONNECTION_SUCCESS,
    INTEGRATIONS_SALESFORCE_DISCONNECTION_SUCCESS,
    INTEGRATIONS_BULK_PUSH_SUCCESS,
    INTEGRATIONS_ZOHO_NOT_CONNECTED_ERR,
    INTEGRATIONS_ZOHO_ALREADY_CONNECTED_ERR,
    INTEGRATIONS_ZOHO_TOKEN_EXPIRED_ERR,
    INTEGRATIONS_ZOHO_CONNECTION_FAILED_ERR,
    INTEGRATIONS_HUBSPOT_NOT_CONNECTED_ERR,
    INTEGRATIONS_HUBSPOT_ALREADY_CONNECTED_ERR,
    INTEGRATIONS_HUBSPOT_TOKEN_EXPIRED_ERR,
    INTEGRATIONS_HUBSPOT_CONNECTION_FAILED_ERR,
    INTEGRATIONS_SALESFORCE_NOT_CONNECTED_ERR,
    INTEGRATIONS_SALESFORCE_ALREADY_CONNECTED_ERR,
    INTEGRATIONS_SALESFORCE_TOKEN_EXPIRED_ERR,
    INTEGRATIONS_SALESFORCE_CONNECTION_FAILED_ERR
}
